import React, { createContext, useContext, useMemo, useState } from 'react';

const LanguageContext = createContext();

export const languages = [
  { code: 'en', label: 'English' },
  { code: 'hi', label: 'हिंदी' },
  { code: 'mr', label: 'मराठी' },
];

const text = {
  en: {
    welcome: 'Welcome, Farmer', smartAssistant: 'Your smart farming assistant', cropDiagnosis: 'Crop Diagnosis', cropDiagnosisDesc: 'Detect crop diseases using AI', weatherSoil: 'Weather & Soil', weatherSoilDesc: 'Check weather and soil conditions', mandiPrices: 'Mandi Prices', mandiPricesDesc: 'Find current market prices', farmAdvisory: 'Farm Advisory', farmAdvisoryDesc: 'Get irrigation and fertilizer advice', farmerServices: 'Farmer Services', farmerServicesDesc: 'Access important government services', language: 'Language preference', chooseLanguage: 'Choose your preferred language', createAccount: 'Create account', profile: 'My Profile', profileDetails: 'Profile details', changePhoto: 'Change profile picture', fullName: 'Full name', username: 'Username', contact: 'Email or phone number', password: 'Password', confirmPassword: 'Confirm password', location: 'Location', soilType: 'Soil type', cropType: 'Crop type', landSize: 'Land size', completeProfile: 'Complete profile', backToRegistration: 'Back to registration', login: 'Log in', welcomeBack: 'Welcome back', createYourAccount: 'Create your account', tellUsFarm: 'Tell us about your farm', mandiSubtitle: "Check today's crop market prices", searchCrop: 'Search crop...', mandiLocation: 'Mandi Location', pricesUpdated: 'Prices updated today', todaysPrices: "Today's Prices", priceInformation: 'Price Information', min: 'Min', max: 'Max', perQuintal: '/ Quintal', noCrop: 'No crop found', farmerServicesSubtitle: 'Important government services for farmers', cropUpload: 'Upload a photo of your crop to detect possible diseases using AI.', cropDetection: 'Crop Disease Detection', cropPhotoHelp: 'Take a clear photo of the affected part of your crop. Our AI will analyze the image and provide possible disease information.', takePhoto: 'Take a Photo', chooseGallery: 'Choose from Gallery', diagnoseCrop: 'Diagnose Crop', back: 'Back',
  },
  hi: {
    welcome: 'स्वागत है, किसान', smartAssistant: 'आपका स्मार्ट कृषि सहायक', cropDiagnosis: 'फसल निदान', cropDiagnosisDesc: 'AI से फसल रोगों का पता लगाएं', weatherSoil: 'मौसम और मिट्टी', weatherSoilDesc: 'मौसम और मिट्टी की स्थिति देखें', mandiPrices: 'मंडी भाव', mandiPricesDesc: 'वर्तमान बाजार भाव जानें', farmAdvisory: 'कृषि सलाह', farmAdvisoryDesc: 'सिंचाई और उर्वरक सलाह पाएं', farmerServices: 'किसान सेवाएं', farmerServicesDesc: 'महत्वपूर्ण सरकारी सेवाएं पाएं', language: 'भाषा की पसंद', chooseLanguage: 'अपनी पसंदीदा भाषा चुनें', createAccount: 'खाता बनाएं', profile: 'मेरी प्रोफ़ाइल', profileDetails: 'प्रोफ़ाइल विवरण', changePhoto: 'प्रोफ़ाइल फ़ोटो बदलें', fullName: 'पूरा नाम', username: 'उपयोगकर्ता नाम', contact: 'ईमेल या फ़ोन नंबर', password: 'पासवर्ड', confirmPassword: 'पासवर्ड की पुष्टि करें', location: 'स्थान', soilType: 'मिट्टी का प्रकार', cropType: 'फसल का प्रकार', landSize: 'भूमि का आकार', completeProfile: 'प्रोफ़ाइल पूरी करें', backToRegistration: 'पंजीकरण पर वापस जाएं', login: 'लॉग इन', welcomeBack: 'वापसी पर स्वागत है', createYourAccount: 'अपना खाता बनाएं', tellUsFarm: 'अपने खेत के बारे में बताएं', mandiSubtitle: 'आज के फसल बाजार भाव देखें', searchCrop: 'फसल खोजें...', mandiLocation: 'मंडी का स्थान', pricesUpdated: 'भाव आज अपडेट किए गए', todaysPrices: 'आज के भाव', priceInformation: 'भाव की जानकारी', min: 'न्यूनतम', max: 'अधिकतम', perQuintal: '/ क्विंटल', noCrop: 'कोई फसल नहीं मिली', farmerServicesSubtitle: 'किसानों के लिए महत्वपूर्ण सरकारी सेवाएं', cropUpload: 'संभावित रोग पहचानने के लिए अपनी फसल की फोटो अपलोड करें।', cropDetection: 'फसल रोग पहचान', cropPhotoHelp: 'फसल के प्रभावित भाग की साफ फोटो लें। हमारा AI तस्वीर का विश्लेषण कर रोग की जानकारी देगा।', takePhoto: 'फोटो लें', chooseGallery: 'गैलरी से चुनें', diagnoseCrop: 'फसल की जांच करें', back: 'वापस',
  },
  mr: {
    welcome: 'स्वागत आहे, शेतकरी', smartAssistant: 'तुमचा स्मार्ट शेती सहाय्यक', cropDiagnosis: 'पीक निदान', cropDiagnosisDesc: 'AI सह पिकांचे रोग ओळखा', weatherSoil: 'हवामान आणि माती', weatherSoilDesc: 'हवामान आणि मातीची स्थिती पहा', mandiPrices: 'मंडीचे भाव', mandiPricesDesc: 'सध्याचे बाजार भाव पहा', farmAdvisory: 'शेती सल्ला', farmAdvisoryDesc: 'सिंचन व खताचा सल्ला मिळवा', farmerServices: 'शेतकरी सेवा', farmerServicesDesc: 'महत्त्वाच्या सरकारी सेवा मिळवा', language: 'भाषेची निवड', chooseLanguage: 'तुमची पसंतीची भाषा निवडा', createAccount: 'खाते तयार करा', profile: 'माझे प्रोफाइल', profileDetails: 'प्रोफाइल तपशील', changePhoto: 'प्रोफाइल फोटो बदला', fullName: 'पूर्ण नाव', username: 'वापरकर्तानाव', contact: 'ईमेल किंवा फोन नंबर', password: 'पासवर्ड', confirmPassword: 'पासवर्डची पुष्टी करा', location: 'स्थान', soilType: 'मातीचा प्रकार', cropType: 'पिकाचा प्रकार', landSize: 'जमिनीचे क्षेत्रफळ', completeProfile: 'प्रोफाइल पूर्ण करा', backToRegistration: 'नोंदणीकडे परत जा', login: 'लॉग इन', welcomeBack: 'पुन्हा स्वागत आहे', createYourAccount: 'तुमचे खाते तयार करा', tellUsFarm: 'तुमच्या शेताबद्दल सांगा', mandiSubtitle: 'आजचे पीक बाजार भाव पहा', searchCrop: 'पीक शोधा...', mandiLocation: 'मंडीचे ठिकाण', pricesUpdated: 'भाव आज अद्ययावत केले', todaysPrices: 'आजचे भाव', priceInformation: 'भावाची माहिती', min: 'किमान', max: 'कमाल', perQuintal: '/ क्विंटल', noCrop: 'पीक सापडले नाही', farmerServicesSubtitle: 'शेतकऱ्यांसाठी महत्त्वाच्या सरकारी सेवा', cropUpload: 'संभाव्य रोग ओळखण्यासाठी पिकाचा फोटो अपलोड करा.', cropDetection: 'पीक रोग ओळख', cropPhotoHelp: 'पिकाच्या बाधित भागाचा स्पष्ट फोटो घ्या. आमचे AI चित्राचे विश्लेषण करून रोगाची माहिती देईल.', takePhoto: 'फोटो घ्या', chooseGallery: 'गॅलरीतून निवडा', diagnoseCrop: 'पीक तपासा', back: 'मागे',
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en');
  const value = useMemo(() => ({ language, setLanguage, t: (key) => text[language]?.[key] || text.en[key] || key }), [language]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export const useLanguage = () => useContext(LanguageContext);
