import React, { createContext, useContext, useMemo, useState } from 'react';

const LanguageContext = createContext();

export const languages = [
  { code: 'en', label: 'English' },
  { code: 'hi', label: 'हिंदी' },
  { code: 'mr', label: 'मराठी' },
];

const text = {
  en: {
    welcome: 'Welcome, Farmer', smartAssistant: 'Your smart farming assistant', cropDiagnosis: 'Crop Diagnosis', cropDiagnosisDesc: 'Detect crop diseases using AI', weatherSoil: 'Weather', weatherSoilDesc: 'Check local weather conditions', mandiPrices: 'Mandi Prices', mandiPricesDesc: 'Find current market prices', farmAdvisory: 'Farm Advisory', farmAdvisoryDesc: 'Get irrigation and fertilizer advice', farmerServices: 'Farmer Services', farmerServicesDesc: 'Access important government services', language: 'Language preference', chooseLanguage: 'Choose your preferred language', createAccount: 'Create account', profile: 'My Profile', profileDetails: 'Profile details', changePhoto: 'Change profile picture', fullName: 'Full name', username: 'Username', contact: 'Email or phone number', password: 'Password', confirmPassword: 'Confirm password', location: 'Location', soilType: 'Soil type', cropType: 'Crop type', landSize: 'Land size', completeProfile: 'Complete profile', backToRegistration: 'Back to registration', login: 'Log in', welcomeBack: 'Welcome back', createYourAccount: 'Create your account', tellUsFarm: 'Tell us about your farm', mandiSubtitle: "Check today's crop market prices", searchCrop: 'Search crop...', mandiLocation: 'Mandi Location', pricesUpdated: 'Prices updated today', todaysPrices: "Today's Prices", priceInformation: 'Price Information', min: 'Min', max: 'Max', perQuintal: '/ Quintal', noCrop: 'No crop found', farmerServicesSubtitle: 'Important government services for farmers', cropUpload: 'Upload a photo of your crop to detect possible diseases using AI.', cropDetection: 'Crop Disease Detection', cropPhotoHelp: 'Take a clear photo of the affected part of your crop. Our AI will analyze the image and provide possible disease information.', takePhoto: 'Take a Photo', chooseGallery: 'Choose from Gallery', diagnoseCrop: 'Diagnose Crop', back: 'Back',
  },
  hi: {
    welcome: 'स्वागत है, किसान', smartAssistant: 'आपका स्मार्ट कृषि सहायक', cropDiagnosis: 'फसल निदान', cropDiagnosisDesc: 'AI से फसल रोगों का पता लगाएं', weatherSoil: 'मौसम', weatherSoilDesc: 'स्थानीय मौसम की स्थिति देखें', mandiPrices: 'मंडी भाव', mandiPricesDesc: 'वर्तमान बाजार भाव जानें', farmAdvisory: 'कृषि सलाह', farmAdvisoryDesc: 'सिंचाई और उर्वरक सलाह पाएं', farmerServices: 'किसान सेवाएं', farmerServicesDesc: 'महत्वपूर्ण सरकारी सेवाएं पाएं', language: 'भाषा की पसंद', chooseLanguage: 'अपनी पसंदीदा भाषा चुनें', createAccount: 'खाता बनाएं', profile: 'मेरी प्रोफ़ाइल', profileDetails: 'प्रोफ़ाइल विवरण', changePhoto: 'प्रोफ़ाइल फ़ोटो बदलें', fullName: 'पूरा नाम', username: 'उपयोगकर्ता नाम', contact: 'ईमेल या फ़ोन नंबर', password: 'पासवर्ड', confirmPassword: 'पासवर्ड की पुष्टि करें', location: 'स्थान', soilType: 'मिट्टी का प्रकार', cropType: 'फसल का प्रकार', landSize: 'भूमि का आकार', completeProfile: 'प्रोफ़ाइल पूरी करें', backToRegistration: 'पंजीकरण पर वापस जाएं', login: 'लॉग इन', welcomeBack: 'वापसी पर स्वागत है', createYourAccount: 'अपना खाता बनाएं', tellUsFarm: 'अपने खेत के बारे में बताएं', mandiSubtitle: 'आज के फसल बाजार भाव देखें', searchCrop: 'फसल खोजें...', mandiLocation: 'मंडी का स्थान', pricesUpdated: 'भाव आज अपडेट किए गए', todaysPrices: 'आज के भाव', priceInformation: 'भाव की जानकारी', min: 'न्यूनतम', max: 'अधिकतम', perQuintal: '/ क्विंटल', noCrop: 'कोई फसल नहीं मिली', farmerServicesSubtitle: 'किसानों के लिए महत्वपूर्ण सरकारी सेवाएं', cropUpload: 'संभावित रोग पहचानने के लिए अपनी फसल की फोटो अपलोड करें।', cropDetection: 'फसल रोग पहचान', cropPhotoHelp: 'फसल के प्रभावित भाग की साफ फोटो लें। हमारा AI तस्वीर का विश्लेषण कर रोग की जानकारी देगा।', takePhoto: 'फोटो लें', chooseGallery: 'गैलरी से चुनें', diagnoseCrop: 'फसल की जांच करें', back: 'वापस',
  },
  mr: {
    welcome: 'स्वागत आहे, शेतकरी', smartAssistant: 'तुमचा स्मार्ट शेती सहाय्यक', cropDiagnosis: 'पीक निदान', cropDiagnosisDesc: 'AI सह पिकांचे रोग ओळखा', weatherSoil: 'हवामान', weatherSoilDesc: 'स्थानिक हवामान स्थिती पहा', mandiPrices: 'मंडीचे भाव', mandiPricesDesc: 'सध्याचे बाजार भाव पहा', farmAdvisory: 'शेती सल्ला', farmAdvisoryDesc: 'सिंचन व खताचा सल्ला मिळवा', farmerServices: 'शेतकरी सेवा', farmerServicesDesc: 'महत्त्वाच्या सरकारी सेवा मिळवा', language: 'भाषेची निवड', chooseLanguage: 'तुमची पसंतीची भाषा निवडा', createAccount: 'खाते तयार करा', profile: 'माझे प्रोफाइल', profileDetails: 'प्रोफाइल तपशील', changePhoto: 'प्रोफाइल फोटो बदला', fullName: 'पूर्ण नाव', username: 'वापरकर्तानाव', contact: 'ईमेल किंवा फोन नंबर', password: 'पासवर्ड', confirmPassword: 'पासवर्डची पुष्टी करा', location: 'स्थान', soilType: 'मातीचा प्रकार', cropType: 'पिकाचा प्रकार', landSize: 'जमिनीचे क्षेत्रफळ', completeProfile: 'प्रोफाइल पूर्ण करा', backToRegistration: 'नोंदणीकडे परत जा', login: 'लॉग इन', welcomeBack: 'पुन्हा स्वागत आहे', createYourAccount: 'तुमचे खाते तयार करा', tellUsFarm: 'तुमच्या शेताबद्दल सांगा', mandiSubtitle: 'आजचे पीक बाजार भाव पहा', searchCrop: 'पीक शोधा...', mandiLocation: 'मंडीचे ठिकाण', pricesUpdated: 'भाव आज अद्ययावत केले', todaysPrices: 'आजचे भाव', priceInformation: 'भावाची माहिती', min: 'किमान', max: 'कमाल', perQuintal: '/ क्विंटल', noCrop: 'पीक सापडले नाही', farmerServicesSubtitle: 'शेतकऱ्यांसाठी महत्त्वाच्या सरकारी सेवा', cropUpload: 'संभाव्य रोग ओळखण्यासाठी पिकाचा फोटो अपलोड करा.', cropDetection: 'पीक रोग ओळख', cropPhotoHelp: 'पिकाच्या बाधित भागाचा स्पष्ट फोटो घ्या. आमचे AI चित्राचे विश्लेषण करून रोगाची माहिती देईल.', takePhoto: 'फोटो घ्या', chooseGallery: 'गॅलरीतून निवडा', diagnoseCrop: 'पीक तपासा', back: 'मागे',
  },
};

const regionalText = {
  gu: { welcome: 'સ્વાગત છે, ખેડૂત', smartAssistant: 'તમારો સ્માર્ટ ખેતી સહાયક', cropDiagnosis: 'પાક નિદાન', weatherSoil: 'હવામાન', mandiPrices: 'મંડી ભાવ', farmAdvisory: 'ખેતી સલાહ', farmerServices: 'ખેડૂત સેવાઓ', profile: 'મારી પ્રોફાઇલ', language: 'ભાષા પસંદગી', login: 'લૉગ ઇન' },
  ta: { welcome: 'வரவேற்கிறோம், விவசாயி', smartAssistant: 'உங்கள் ஸ்மார்ட் விவசாய உதவியாளர்', cropDiagnosis: 'பயிர் கண்டறிதல்', weatherSoil: 'வானிலை', mandiPrices: 'மண்டி விலைகள்', farmAdvisory: 'பண்ணை ஆலோசனை', farmerServices: 'விவசாயி சேவைகள்', profile: 'என் சுயவிவரம்', language: 'மொழி விருப்பம்', login: 'உள்நுழைய' },
  te: { welcome: 'స్వాగతం, రైతు', smartAssistant: 'మీ స్మార్ట్ వ్యవసాయ సహాయకుడు', cropDiagnosis: 'పంట నిర్ధారణ', weatherSoil: 'వాతావరణం', mandiPrices: 'మండి ధరలు', farmAdvisory: 'వ్యవసాయ సలహా', farmerServices: 'రైతు సేవలు', profile: 'నా ప్రొఫైల్', language: 'భాష ప్రాధాన్యత', login: 'లాగిన్' },
  kn: { welcome: 'ಸ್ವಾಗತ, ರೈತ', smartAssistant: 'ನಿಮ್ಮ ಸ್ಮಾರ್ಟ್ ಕೃಷಿ ಸಹಾಯಕ', cropDiagnosis: 'ಬೆಳೆ ರೋಗನಿರ್ಣಯ', weatherSoil: 'ಹವಾಮಾನ', mandiPrices: 'ಮಂಡಿ ಬೆಲೆಗಳು', farmAdvisory: 'ಕೃಷಿ ಸಲಹೆ', farmerServices: 'ರೈತ ಸೇವೆಗಳು', profile: 'ನನ್ನ ಪ್ರೊಫೈಲ್', language: 'ಭಾಷೆ ಆಯ್ಕೆ', login: 'ಲಾಗಿನ್' },
  bn: { welcome: 'স্বাগতম, কৃষক', smartAssistant: 'আপনার স্মার্ট কৃষি সহায়ক', cropDiagnosis: 'ফসল নির্ণয়', weatherSoil: 'আবহাওয়া', mandiPrices: 'মন্ডি দাম', farmAdvisory: 'কৃষি পরামর্শ', farmerServices: 'কৃষক পরিষেবা', profile: 'আমার প্রোফাইল', language: 'ভাষার পছন্দ', login: 'লগ ইন' },
  pa: { welcome: 'ਜੀ ਆਇਆਂ ਨੂੰ, ਕਿਸਾਨ', smartAssistant: 'ਤੁਹਾਡਾ ਸਮਾਰਟ ਖੇਤੀ ਸਹਾਇਕ', cropDiagnosis: 'ਫਸਲ ਜਾਂਚ', weatherSoil: 'ਮੌਸਮ', mandiPrices: 'ਮੰਡੀ ਭਾਅ', farmAdvisory: 'ਖੇਤੀ ਸਲਾਹ', farmerServices: 'ਕਿਸਾਨ ਸੇਵਾਵਾਂ', profile: 'ਮੇਰੀ ਪ੍ਰੋਫਾਈਲ', language: 'ਭਾਸ਼ਾ ਪਸੰਦ', login: 'ਲਾਗ ਇਨ' },
  ml: { welcome: 'സ്വാഗതം, കർഷകാ', smartAssistant: 'നിങ്ങളുടെ സ്മാർട്ട് കൃഷി സഹായി', cropDiagnosis: 'വിള പരിശോധന', weatherSoil: 'കാലാവസ്ഥ', mandiPrices: 'മണ്ടി വിലകൾ', farmAdvisory: 'കൃഷി ഉപദേശം', farmerServices: 'കർഷക സേവനങ്ങൾ', profile: 'എന്റെ പ്രൊഫൈൽ', language: 'ഭാഷാ മുൻഗണന', login: 'ലോഗിൻ' },
  or: { welcome: 'ସ୍ୱାଗତ, କୃଷକ', smartAssistant: 'ଆପଣଙ୍କ ସ୍ମାର୍ଟ କୃଷି ସହାୟକ', cropDiagnosis: 'ଫସଲ ନିର୍ଣ୍ଣୟ', weatherSoil: 'ପାଣିପାଗ', mandiPrices: 'ମଣ୍ଡି ଦର', farmAdvisory: 'କୃଷି ପରାମର୍ଶ', farmerServices: 'କୃଷକ ସେବା', profile: 'ମୋ ପ୍ରୋଫାଇଲ', language: 'ଭାଷା ପସନ୍ଦ', login: 'ଲଗ ଇନ' },
  as: { welcome: 'স্বাগতম, কৃষক', smartAssistant: 'আপোনাৰ স্মাৰ্ট কৃষি সহায়ক', cropDiagnosis: 'শস্য নিৰ্ণয়', weatherSoil: 'বতৰ', mandiPrices: 'মাণ্ডি মূল্য', farmAdvisory: 'কৃষি পৰামৰ্শ', farmerServices: 'কৃষক সেৱা', profile: 'মোৰ প্ৰফাইল', language: 'ভাষা পছন্দ', login: 'লগ ইন' },
};

Object.assign(text.en, { dailyPrices: 'Daily prices', varietyWise: 'Variety-wise', localPrices: 'My local prices', latestRecords: 'Latest market records from across India', market: 'Market', districtState: 'District / State', variety: 'Variety', arrivalDate: 'Arrival date', modalPrice: 'Modal price', priceRange: 'Min – Max', addLocalPrice: 'Add your local market price', saveLocalPrice: 'Save local price', farmAdvisoryTitle: 'Farm Advisory', advisorySubtitle: 'Enter your soil-test NPK values and ask a crop question.', nitrogen: 'Nitrogen (N)', phosphorus: 'Phosphorus (P)', potassium: 'Potassium (K)', askCrop: 'Ask about your crop', getAdvice: 'Get crop advice', advisory: 'Advisory', logout: 'Log out' });
Object.assign(text.en, { enterSoilValue: 'Enter soil-test value', cropQuestionExample: 'e.g. Yellow leaves on tomato', advisoryDisclaimer: 'This is general guidance, not a fertilizer prescription. Confirm units and dosage with a soil lab or local agriculture officer.' });
Object.assign(text.hi, { dailyPrices: 'दैनिक भाव', varietyWise: 'किस्म के अनुसार', localPrices: 'मेरे स्थानीय भाव', latestRecords: 'भारत भर के नवीनतम मंडी रिकॉर्ड', market: 'मंडी', districtState: 'जिला / राज्य', variety: 'किस्म', arrivalDate: 'आगमन तिथि', modalPrice: 'मॉडल भाव', priceRange: 'न्यूनतम – अधिकतम', addLocalPrice: 'स्थानीय बाजार भाव जोड़ें', saveLocalPrice: 'स्थानीय भाव सहेजें', farmAdvisoryTitle: 'कृषि सलाह', advisorySubtitle: 'मिट्टी के NPK मान भरें और फसल से जुड़ा प्रश्न पूछें।', nitrogen: 'नाइट्रोजन (N)', phosphorus: 'फास्फोरस (P)', potassium: 'पोटैशियम (K)', askCrop: 'अपनी फसल के बारे में पूछें', getAdvice: 'सलाह प्राप्त करें', advisory: 'सलाह', logout: 'लॉग आउट' });
Object.assign(text.mr, { dailyPrices: 'दैनंदिन भाव', varietyWise: 'वाणानुसार', localPrices: 'माझे स्थानिक भाव', latestRecords: 'भारतातील नवीनतम बाजार नोंदी', market: 'बाजार', districtState: 'जिल्हा / राज्य', variety: 'वाण', arrivalDate: 'आवक तारीख', modalPrice: 'मॉडल भाव', priceRange: 'किमान – कमाल', addLocalPrice: 'स्थानिक बाजार भाव जोडा', saveLocalPrice: 'स्थानिक भाव जतन करा', farmAdvisoryTitle: 'शेती सल्ला', advisorySubtitle: 'मातीचे NPK मूल्य भरा आणि पिकाबद्दल प्रश्न विचारा.', nitrogen: 'नायट्रोजन (N)', phosphorus: 'स्फुरद (P)', potassium: 'पालाश (K)', askCrop: 'तुमच्या पिकाबद्दल विचारा', getAdvice: 'सल्ला मिळवा', advisory: 'सल्ला', logout: 'लॉग आउट' });

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en');
  const value = useMemo(() => ({ language, setLanguage, t: (key) => text[language]?.[key] || regionalText[language]?.[key] || text.en[key] || key }), [language]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export const useLanguage = () => useContext(LanguageContext);
